USE data_extracts;

-- ahui 6/2/2020

DROP PROCEDURE IF EXISTS createGH2Dataset3a;

DELIMITER //
CREATE PROCEDURE createGH2Dataset3a()
BEGIN

-- Brain_Consortium_Diagnoses

DROP TABLE IF EXISTS gh2_brain2dataset;

CREATE TABLE gh2_brain2dataset (
    Pseudo_id                                                            VARCHAR(255) NULL,  
    Pseudo_NHSNumber                                                     VARCHAR(255) NULL,
    NeurolepticMalignantSyndromeECode                                    VARCHAR(50) NULL, 
    NeurolepticMalignantSyndromeETerm                                    VARCHAR(200) NULL,
    NeurolepticMalignantSyndromeEDate                                    VARCHAR(50) NULL, 
    ManiaManicEpisodeECode                                               VARCHAR(50) NULL, 
    ManiaManicEpisodeETerm                                               VARCHAR(200) NULL,
    ManiaManicEpisodeEDate                                               VARCHAR(50) NULL, 
    BipolarAffectiveDisorderECode                                        VARCHAR(50) NULL, 
    BipolarAffectiveDisorderETerm                                        VARCHAR(200) NULL,
    BipolarAffectiveDisorderEDate                                        VARCHAR(50) NULL, 
    DepressionAsPerIcdECode                                              VARCHAR(50) NULL, 
    DepressionAsPerIcdETerm                                              VARCHAR(200) NULL,
    DepressionAsPerIcdEDate                                              VARCHAR(50) NULL, 
    DepressiveDisorderECode                                              VARCHAR(50) NULL, 
    DepressiveDisorderETerm                                              VARCHAR(200) NULL,
    DepressiveDisorderEDate                                              VARCHAR(50) NULL, 
    DepressiveEpisodeECode                                               VARCHAR(50) NULL, 
    DepressiveEpisodeETerm                                               VARCHAR(200) NULL,
    DepressiveEpisodeEDate                                               VARCHAR(50) NULL, 
    RecurrentDepressionECode                                             VARCHAR(50) NULL, 
    RecurrentDepressionETerm                                             VARCHAR(200) NULL,
    RecurrentDepressionEDate                                             VARCHAR(50) NULL, 
    DysthmiaECode                                                        VARCHAR(50) NULL, 
    DysthmiaETerm                                                        VARCHAR(200) NULL,
    DysthmiaEDate                                                        VARCHAR(50) NULL, 
    CyclothymiaECode                                                     VARCHAR(50) NULL, 
    CyclothymiaETerm                                                     VARCHAR(200) NULL,
    CyclothymiaEDate                                                     VARCHAR(50) NULL, 
    SeasonalAffectiveDisorderECode                                       VARCHAR(50) NULL, 
    SeasonalAffectiveDisorderETerm                                       VARCHAR(200) NULL,
    SeasonalAffectiveDisorderEDate                                       VARCHAR(50) NULL, 
    NeuroticDisordersECode                                               VARCHAR(50) NULL, 
    NeuroticDisordersETerm                                               VARCHAR(200) NULL,
    NeuroticDisordersEDate                                               VARCHAR(50) NULL, 
    PostpartumNatalDepressionECode                                       VARCHAR(50) NULL, 
    PostpartumNatalDepressionETerm                                       VARCHAR(200) NULL,
    PostpartumNatalDepressionEDate                                       VARCHAR(50) NULL, 
    PeurperalPsychosisECode                                              VARCHAR(50) NULL, 
    PeurperalPsychosisETerm                                              VARCHAR(200) NULL,
    PeurperalPsychosisEDate                                              VARCHAR(50) NULL, 
    AnxietyECode                                                         VARCHAR(50) NULL, 
    AnxietyETerm                                                         VARCHAR(200) NULL,
    AnxietyEDate                                                         VARCHAR(50) NULL, 
    AcuteStressDisorderECode                                             VARCHAR(50) NULL, 
    AcuteStressDisorderETerm                                             VARCHAR(200) NULL,
    AcuteStressDisorderEDate                                             VARCHAR(50) NULL, 
    GeneralisedAnxietyDisorderECode                                      VARCHAR(50) NULL, 
    GeneralisedAnxietyDisorderETerm                                      VARCHAR(200) NULL,
    GeneralisedAnxietyDisorderEDate                                      VARCHAR(50) NULL, 
    MixedAnxietyDepressionECode                                          VARCHAR(50) NULL, 
    MixedAnxietyDepressionETerm                                          VARCHAR(200) NULL,
    MixedAnxietyDepressionEDate                                          VARCHAR(50) NULL, 
    PtsdECode                                                            VARCHAR(50) NULL, 
    PtsdETerm                                                            VARCHAR(200) NULL,
    PtsdEDate                                                            VARCHAR(50) NULL, 
    OcdECode                                                             VARCHAR(50) NULL, 
    OcdETerm                                                             VARCHAR(200) NULL,
    OcdEDate                                                             VARCHAR(50) NULL, 
    PanicDisorderPanicAttackECode                                        VARCHAR(50) NULL, 
    PanicDisorderPanicAttackETerm                                        VARCHAR(200) NULL,
    PanicDisorderPanicAttackEDate                                        VARCHAR(50) NULL, 
    SocialAnxietyDisorderChildhoodECode                                  VARCHAR(50) NULL, 
    SocialAnxietyDisorderChildhoodETerm                                  VARCHAR(200) NULL,
    SocialAnxietyDisorderChildhoodEDate                                  VARCHAR(50) NULL, 
    AnxietyDisorderChildhoodECode                                        VARCHAR(50) NULL, 
    AnxietyDisorderChildhoodETerm                                        VARCHAR(200) NULL,
    AnxietyDisorderChildhoodEDate                                        VARCHAR(50) NULL, 
    PhobiasECode                                                         VARCHAR(50) NULL, 
    PhobiasETerm                                                         VARCHAR(200) NULL,
    PhobiasEDate                                                         VARCHAR(50) NULL, 
    PhobicDisordersECode                                                 VARCHAR(50) NULL, 
    PhobicDisordersETerm                                                 VARCHAR(200) NULL,
    PhobicDisordersEDate                                                 VARCHAR(50) NULL, 
    SpecificPhobiasECode                                                 VARCHAR(50) NULL, 
    SpecificPhobiasETerm                                                 VARCHAR(200) NULL,
    SpecificPhobiasEDate                                                 VARCHAR(50) NULL, 
    SocialPhobiasECode                                                   VARCHAR(50) NULL, 
    SocialPhobiasETerm                                                   VARCHAR(200) NULL,
    SocialPhobiasEDate                                                   VARCHAR(50) NULL, 
    AgoraphobiaECode                                                     VARCHAR(50) NULL, 
    AgoraphobiaETerm                                                     VARCHAR(200) NULL,
    AgoraphobiaEDate                                                     VARCHAR(50) NULL, 
    DissociativeDisorderConversionDisorderECode                          VARCHAR(50) NULL, 
    DissociativeDisorderConversionDisorderETerm                          VARCHAR(200) NULL,
    DissociativeDisorderConversionDisorderEDate                          VARCHAR(50) NULL, 
    AdjustmentDisorderIncludesAcuteStressReactionECode                   VARCHAR(50) NULL, 
    AdjustmentDisorderIncludesAcuteStressReactionETerm                   VARCHAR(200) NULL,
    AdjustmentDisorderIncludesAcuteStressReactionEDate                   VARCHAR(50) NULL, 
    SomatoformDisorderECode                                              VARCHAR(50) NULL, 
    SomatoformDisorderETerm                                              VARCHAR(200) NULL,
    SomatoformDisorderEDate                                              VARCHAR(50) NULL, 
    SomatizationDisorderECode                                            VARCHAR(50) NULL, 
    SomatizationDisorderETerm                                            VARCHAR(200) NULL,
    SomatizationDisorderEDate                                            VARCHAR(50) NULL, 
    HypochonriacalDisorderECode                                          VARCHAR(50) NULL, 
    HypochonriacalDisorderETerm                                          VARCHAR(200) NULL,
    HypochonriacalDisorderEDate                                          VARCHAR(50) NULL, 
    PsychogenicFatigueECode                                              VARCHAR(50) NULL, 
    PsychogenicFatigueETerm                                              VARCHAR(200) NULL,
    PsychogenicFatigueEDate                                              VARCHAR(50) NULL, 
    MultiplePersonalityDisorderECode                                     VARCHAR(50) NULL, 
    MultiplePersonalityDisorderETerm                                     VARCHAR(200) NULL,
    MultiplePersonalityDisorderEDate                                     VARCHAR(50) NULL, 
    GansersDisorderECode                                                 VARCHAR(50) NULL, 
    GansersDisorderETerm                                                 VARCHAR(200) NULL,
    GansersDisorderEDate                                                 VARCHAR(50) NULL, 
    EatingDisordersECode                                                 VARCHAR(50) NULL, 
    EatingDisordersETerm                                                 VARCHAR(200) NULL,
    EatingDisordersEDate                                                 VARCHAR(50) NULL, 
    BulimiaECode                                                         VARCHAR(50) NULL, 
    BulimiaETerm                                                         VARCHAR(200) NULL,
    BulimiaEDate                                                         VARCHAR(50) NULL, 
    AnorexiaNervosaECode                                                 VARCHAR(50) NULL, 
    AnorexiaNervosaETerm                                                 VARCHAR(200) NULL,
    AnorexiaNervosaEDate                                                 VARCHAR(50) NULL, 
    SubstanceAbuseECode                                                  VARCHAR(50) NULL, 
    SubstanceAbuseETerm                                                  VARCHAR(200) NULL,
    SubstanceAbuseEDate                                                  VARCHAR(50) NULL, 
    AdhdAddECode                                                         VARCHAR(50) NULL, 
    AdhdAddETerm                                                         VARCHAR(200) NULL,
    AdhdAddEDate                                                         VARCHAR(50) NULL, 
    PersonalityDisorderECode                                             VARCHAR(50) NULL, 
    PersonalityDisorderETerm                                             VARCHAR(200) NULL,
    PersonalityDisorderEDate                                             VARCHAR(50) NULL, 
    HabitAndImpulseDisordersECode                                        VARCHAR(50) NULL, 
    HabitAndImpulseDisordersETerm                                        VARCHAR(200) NULL,
    HabitAndImpulseDisordersEDate                                        VARCHAR(50) NULL, 
    LearningDisabilitiesECode                                            VARCHAR(50) NULL, 
    LearningDisabilitiesETerm                                            VARCHAR(200) NULL,
    LearningDisabilitiesEDate                                            VARCHAR(50) NULL, 
    IntellectualDisabilitiesECode                                        VARCHAR(50) NULL, 
    IntellectualDisabilitiesETerm                                        VARCHAR(200) NULL,
    IntellectualDisabilitiesEDate                                        VARCHAR(50) NULL, 
    RettsSyndromeECode                                                   VARCHAR(50) NULL, 
    RettsSyndromeETerm                                                   VARCHAR(200) NULL,
    RettsSyndromeEDate                                                   VARCHAR(50) NULL, 
    AutismAspergersECode                                                 VARCHAR(50) NULL, 
    AutismAspergersETerm                                                 VARCHAR(200) NULL,
    AutismAspergersEDate                                                 VARCHAR(50) NULL, 
    SpeechLanguageDisorderECode                                          VARCHAR(50) NULL, 
    SpeechLanguageDisorderETerm                                          VARCHAR(200) NULL,
    SpeechLanguageDisorderEDate                                          VARCHAR(50) NULL, 
    ConductDisorderECode                                                 VARCHAR(50) NULL, 
    ConductDisorderETerm                                                 VARCHAR(200) NULL,
    ConductDisorderEDate                                                 VARCHAR(50) NULL, 
    TicDisorderECode                                                     VARCHAR(50) NULL, 
    TicDisorderETerm                                                     VARCHAR(200) NULL,
    TicDisorderEDate                                                     VARCHAR(50) NULL, 
    TourettesSyndromeECode                                               VARCHAR(50) NULL, 
    TourettesSyndromeETerm                                               VARCHAR(200) NULL,
    TourettesSyndromeEDate                                               VARCHAR(50) NULL, 
    GenderIdentityDisordersECode                                         VARCHAR(50) NULL, 
    GenderIdentityDisordersETerm                                         VARCHAR(200) NULL,
    GenderIdentityDisordersEDate                                         VARCHAR(50) NULL
);
    
ALTER TABLE gh2_brain2dataset ADD INDEX gh2d3a_pseudoid_idx (pseudo_id);
    
INSERT INTO gh2_brain2dataset (pseudo_id) SELECT DISTINCT group_by FROM cohort_gh2;
    
END//
DELIMITER ;