USE data_extracts;

-- ahui 7/2/2020

DROP PROCEDURE IF EXISTS createGH2Dataset4;

DELIMITER //
CREATE PROCEDURE createGH2Dataset4()
BEGIN

-- Lab Results

DROP TABLE IF EXISTS gh2_labdataset;

CREATE TABLE gh2_labdataset (
    Pseudo_id                                      VARCHAR(255) NULL,
    Pseudo_NHSNUmber                               VARCHAR(255) NULL,
    HbA1cECode                                     VARCHAR(50) NULL, 
    HbA1cETerm                                     VARCHAR(200) NULL, 
    HbA1cEValue                                    VARCHAR(50) NULL, 
    HbA1cEUnit                                     VARCHAR(50) NULL, 
    HbA1cEDate                                     VARCHAR(50) NULL, 
    HbA1cLCode                                     VARCHAR(50) NULL, 
    HbA1cLTerm                                     VARCHAR(200) NULL, 
    HbA1cLValue                                    VARCHAR(50) NULL, 
    HbA1cLUnit                                     VARCHAR(50) NULL, 
    HbA1cLDate                                     VARCHAR(50) NULL, 
    HbA1c6Code                                     VARCHAR(50) NULL, 
    HbA1c6Term                                     VARCHAR(200) NULL, 
    HbA1c6Value                                    VARCHAR(50) NULL, 
    HbA1c6Unit                                     VARCHAR(50) NULL, 
    HbA1c6Date                                     VARCHAR(50) NULL, 
    TotalCholesterolECode                          VARCHAR(50) NULL, 
    TotalCholesterolETerm                          VARCHAR(200) NULL, 
    TotalCholesterolEValue                         VARCHAR(50) NULL, 
    TotalCholesterolEUnit                          VARCHAR(50) NULL, 
    TotalCholesterolEDate                          VARCHAR(50) NULL, 
    TotalCholesterolLCode                          VARCHAR(50) NULL, 
    TotalCholesterolLTerm                          VARCHAR(200) NULL, 
    TotalCholesterolLValue                         VARCHAR(50) NULL, 
    TotalCholesterolLUnit                          VARCHAR(50) NULL, 
    TotalCholesterolLDate                          VARCHAR(50) NULL, 
    TotalCholesterol6Code                          VARCHAR(50) NULL, 
    TotalCholesterol6Term                          VARCHAR(200) NULL, 
    TotalCholesterol6Value                         VARCHAR(50) NULL, 
    TotalCholesterol6Unit                          VARCHAR(50) NULL, 
    TotalCholesterol6Date                          VARCHAR(50) NULL, 
    HDLCholesterolECode                            VARCHAR(50) NULL, 
    HDLCholesterolETerm                            VARCHAR(200) NULL, 
    HDLCholesterolEValue                           VARCHAR(50) NULL, 
    HDLCholesterolEUnit                            VARCHAR(50) NULL, 
    HDLCholesterolEDate                            VARCHAR(50) NULL, 
    HDLCholesterolLCode                            VARCHAR(50) NULL, 
    HDLCholesterolLTerm                            VARCHAR(200) NULL, 
    HDLCholesterolLValue                           VARCHAR(50) NULL, 
    HDLCholesterolLUnit                            VARCHAR(50) NULL, 
    HDLCholesterolLDate                            VARCHAR(50) NULL, 
    HDLCholesterol6Code                            VARCHAR(50) NULL, 
    HDLCholesterol6Term                            VARCHAR(200) NULL, 
    HDLCholesterol6Value                           VARCHAR(50) NULL, 
    HDLCholesterol6Unit                            VARCHAR(50) NULL, 
    HDLCholesterol6Date                            VARCHAR(50) NULL, 
    SerumLDLCholesterolECode                       VARCHAR(50) NULL, 
    SerumLDLCholesterolETerm                       VARCHAR(200) NULL, 
    SerumLDLCholesterolEValue                      VARCHAR(50) NULL, 
    SerumLDLCholesterolEUnit                       VARCHAR(50) NULL, 
    SerumLDLCholesterolEDate                       VARCHAR(50) NULL, 
    SerumLDLCholesterolLCode                       VARCHAR(50) NULL, 
    SerumLDLCholesterolLTerm                       VARCHAR(200) NULL, 
    SerumLDLCholesterolLValue                      VARCHAR(50) NULL, 
    SerumLDLCholesterolLUnit                       VARCHAR(50) NULL, 
    SerumLDLCholesterolLDate                       VARCHAR(50) NULL, 
    SerumLDLCholesterol6Code                       VARCHAR(50) NULL, 
    SerumLDLCholesterol6Term                       VARCHAR(200) NULL, 
    SerumLDLCholesterol6Value                      VARCHAR(50) NULL, 
    SerumLDLCholesterol6Unit                       VARCHAR(50) NULL, 
    SerumLDLCholesterol6Date                       VARCHAR(50) NULL, 
    SerumTriglyceridesECode                        VARCHAR(50) NULL, 
    SerumTriglyceridesETerm                        VARCHAR(200) NULL, 
    SerumTriglyceridesEValue                       VARCHAR(50) NULL, 
    SerumTriglyceridesEUnit                        VARCHAR(50) NULL, 
    SerumTriglyceridesEDate                        VARCHAR(50) NULL, 
    SerumTriglyceridesLCode                        VARCHAR(50) NULL, 
    SerumTriglyceridesLTerm                        VARCHAR(200) NULL, 
    SerumTriglyceridesLValue                       VARCHAR(50) NULL, 
    SerumTriglyceridesLUnit                        VARCHAR(50) NULL, 
    SerumTriglyceridesLDate                        VARCHAR(50) NULL, 
    SerumTriglycerides6Code                        VARCHAR(50) NULL, 
    SerumTriglycerides6Term                        VARCHAR(200) NULL, 
    SerumTriglycerides6Value                       VARCHAR(50) NULL, 
    SerumTriglycerides6Unit                        VARCHAR(50) NULL, 
    SerumTriglycerides6Date                        VARCHAR(50) NULL, 
    UrineProteinCreatinineRatioECode               VARCHAR(50) NULL, 
    UrineProteinCreatinineRatioETerm               VARCHAR(200) NULL, 
    UrineProteinCreatinineRatioEValue              VARCHAR(50) NULL, 
    UrineProteinCreatinineRatioEUnit               VARCHAR(50) NULL, 
    UrineProteinCreatinineRatioEDate               VARCHAR(50) NULL, 
    UrineProteinCreatinineRatioLCode               VARCHAR(50) NULL, 
    UrineProteinCreatinineRatioLTerm               VARCHAR(200) NULL, 
    UrineProteinCreatinineRatioLValue              VARCHAR(50) NULL, 
    UrineProteinCreatinineRatioLUnit               VARCHAR(50) NULL, 
    UrineProteinCreatinineRatioLDate               VARCHAR(50) NULL, 
    UrineAlbuminCreatinineRatioECode               VARCHAR(50) NULL, 
    UrineAlbuminCreatinineRatioETerm               VARCHAR(200) NULL, 
    UrineAlbuminCreatinineRatioEValue              VARCHAR(50) NULL, 
    UrineAlbuminCreatinineRatioEUnit               VARCHAR(50) NULL, 
    UrineAlbuminCreatinineRatioEDate               VARCHAR(50) NULL, 
    UrineAlbuminCreatinineRatioLCode               VARCHAR(50) NULL, 
    UrineAlbuminCreatinineRatioLTerm               VARCHAR(200) NULL, 
    UrineAlbuminCreatinineRatioLValue              VARCHAR(50) NULL, 
    UrineAlbuminCreatinineRatioLUnit               VARCHAR(50) NULL, 
    UrineAlbuminCreatinineRatioLDate               VARCHAR(50) NULL, 
    UrineAlbuminECode                              VARCHAR(50) NULL, 
    UrineAlbuminETerm                              VARCHAR(200) NULL, 
    UrineAlbuminEValue                             VARCHAR(50) NULL, 
    UrineAlbuminEUnit                              VARCHAR(50) NULL, 
    UrineAlbuminEDate                              VARCHAR(50) NULL, 
    UrineAlbuminLCode                              VARCHAR(50) NULL, 
    UrineAlbuminLTerm                              VARCHAR(200) NULL, 
    UrineAlbuminLValue                             VARCHAR(50) NULL, 
    UrineAlbuminLUnit                              VARCHAR(50) NULL, 
    UrineAlbuminLDate                              VARCHAR(50) NULL, 
    SerumCreatinineECode                           VARCHAR(50) NULL, 
    SerumCreatinineETerm                           VARCHAR(200) NULL, 
    SerumCreatinineEValue                          VARCHAR(50) NULL, 
    SerumCreatinineEUnit                           VARCHAR(50) NULL, 
    SerumCreatinineEDate                           VARCHAR(50) NULL, 
    SerumCreatinineLCode                           VARCHAR(50) NULL, 
    SerumCreatinineLTerm                           VARCHAR(200) NULL, 
    SerumCreatinineLValue                          VARCHAR(50) NULL, 
    SerumCreatinineLUnit                           VARCHAR(50) NULL, 
    SerumCreatinineLDate                           VARCHAR(50) NULL, 
    eGFRECode                                      VARCHAR(50) NULL, 
    eGFRETerm                                      VARCHAR(200) NULL, 
    eGFREValue                                     VARCHAR(50) NULL, 
    eGFREUnit                                      VARCHAR(50) NULL, 
    eGFREDate                                      VARCHAR(50) NULL, 
    eGFRLCode                                      VARCHAR(50) NULL, 
    eGFRLTerm                                      VARCHAR(200) NULL, 
    eGFRLValue                                     VARCHAR(50) NULL, 
    eGFRLUnit                                      VARCHAR(50) NULL, 
    eGFRLDate                                      VARCHAR(50) NULL, 
    GADLCode                                       VARCHAR(50) NULL, 
    GADLTerm                                       VARCHAR(200) NULL, 
    GADLValue                                      VARCHAR(50) NULL, 
    GADLUnit                                       VARCHAR(50) NULL, 
    GADLDate                                       VARCHAR(50) NULL, 
    IsletCellAntibodyLevelLCode                    VARCHAR(50) NULL, 
    IsletCellAntibodyLevelLTerm                    VARCHAR(200) NULL, 
    IsletCellAntibodyLevelLValue                   VARCHAR(50) NULL, 
    IsletCellAntibodyLevelLUnit                    VARCHAR(50) NULL, 
    IsletCellAntibodyLevelLDate                    VARCHAR(50) NULL, 
    IA2LCode                                       VARCHAR(50) NULL, 
    IA2LTerm                                       VARCHAR(200) NULL, 
    IA2LValue                                      VARCHAR(50) NULL, 
    IA2LUnit                                       VARCHAR(50) NULL, 
    IA2LDate                                       VARCHAR(50) NULL, 
    CoeliacAutoantibodyProfileLCode                VARCHAR(50) NULL, 
    CoeliacAutoantibodyProfileLTerm                VARCHAR(200) NULL, 
    CoeliacAutoantibodyProfileLValue               VARCHAR(50) NULL, 
    CoeliacAutoantibodyProfileLUnit                VARCHAR(50) NULL, 
    CoeliacAutoantibodyProfileLDate                VARCHAR(50) NULL, 
    AntiThyroidPeroxidaseLCode                     VARCHAR(50) NULL, 
    AntiThyroidPeroxidaseLTerm                     VARCHAR(200) NULL, 
    AntiThyroidPeroxidaseLValue                    VARCHAR(50) NULL, 
    AntiThyroidPeroxidaseLUnit                     VARCHAR(50) NULL, 
    AntiThyroidPeroxidaseLDate                     VARCHAR(50) NULL, 
    CpeptideLCode                                  VARCHAR(50) NULL, 
    CpeptideLTerm                                  VARCHAR(200) NULL, 
    CpeptideLValue                                 VARCHAR(50) NULL, 
    CpeptideLUnit                                  VARCHAR(50) NULL, 
    CpeptideLDate                                  VARCHAR(50) NULL, 
    SerumInsulinLCode                              VARCHAR(50) NULL, 
    SerumInsulinLTerm                              VARCHAR(200) NULL, 
    SerumInsulinLValue                             VARCHAR(50) NULL, 
    SerumInsulinLUnit                              VARCHAR(50) NULL, 
    SerumInsulinLDate                              VARCHAR(50) NULL, 
    SerumALTAlanineAminotransferaseLevelLCode      VARCHAR(50) NULL, 
    SerumALTAlanineAminotransferaseLevelLTerm      VARCHAR(200) NULL, 
    SerumALTAlanineAminotransferaseLevelLValue     VARCHAR(50) NULL, 
    SerumALTAlanineAminotransferaseLevelLUnit      VARCHAR(50) NULL, 
    SerumALTAlanineAminotransferaseLevelLDate      VARCHAR(50) NULL, 
    ASTSerumLevelLCode                             VARCHAR(50) NULL, 
    ASTSerumLevelLTerm                             VARCHAR(200) NULL, 
    ASTSerumLevelLValue                            VARCHAR(50) NULL, 
    ASTSerumLevelLUnit                             VARCHAR(50) NULL, 
    ASTSerumLevelLDate                             VARCHAR(50) NULL, 
    T4LCode                                        VARCHAR(50) NULL, 
    T4LTerm                                        VARCHAR(200) NULL, 
    T4LValue                                       VARCHAR(50) NULL, 
    T4LUnit                                        VARCHAR(50) NULL, 
    T4LDate                                        VARCHAR(50) NULL, 
    TSHLCode                                       VARCHAR(50) NULL, 
    TSHLTerm                                       VARCHAR(200) NULL, 
    TSHLValue                                      VARCHAR(50) NULL, 
    TSHLUnit                                       VARCHAR(50) NULL, 
    TSHLDate                                       VARCHAR(50) NULL
);  
    
ALTER TABLE gh2_labdataset ADD INDEX gh2d4_pseudoid_idx (pseudo_id); 
INSERT INTO gh2_labdataset (pseudo_id) SELECT DISTINCT group_by FROM cohort_gh2;
    
END//
DELIMITER ;
    
     