USE data_extracts;

-- ahui 5/2/2020

DROP PROCEDURE IF EXISTS createGH2Dataset1;

DELIMITER //
CREATE PROCEDURE createGH2Dataset1()
BEGIN

-- Demographics
-- Diagnoses (1)

DROP TABLE IF EXISTS gh2_diagnoses1dataset;

CREATE TABLE gh2_diagnoses1dataset (
    Pseudo_id                                              VARCHAR(255) NULL,
    Pseudo_NHSNumber                                       VARCHAR(255) NULL,
    FHDiabetesLCode                                        VARCHAR(50) NULL,   
    FHDiabetesLTerm                                        VARCHAR(200) NULL,
    FHDiabetesLDate                                        VARCHAR(50) NULL,
    FHIHDLCode                                             VARCHAR(50) NULL,
    FHIHDLTerm                                             VARCHAR(200) NULL,
    FHIHDLDate                                             VARCHAR(50) NULL,
    FHFHLCode                                              VARCHAR(50) NULL,
    FHFHLTerm                                              VARCHAR(200) NULL,
    FHFHLDate                                              VARCHAR(50) NULL,
    FHTXLCode                                              VARCHAR(50) NULL,
    FHTXLTerm                                              VARCHAR(200) NULL,
    FHTXLDate                                              VARCHAR(50) NULL,
    Type1DiabetesECode                                     VARCHAR(50) NULL,
    Type1DiabetesETerm                                     VARCHAR(200) NULL,
    Type1DiabetesEDate                                     VARCHAR(50) NULL,
    Type2DiabetesECode                                     VARCHAR(50) NULL,
    Type2DiabetesETerm                                     VARCHAR(200) NULL,
    Type2DiabetesEDate                                     VARCHAR(50) NULL,
    SecondaryDiabetesECode                                 VARCHAR(50) NULL,
    SecondaryDiabetesETerm                                 VARCHAR(200) NULL,
    SecondaryDiabetesEDate                                 VARCHAR(50) NULL,
    OtherDiabetesECode                                     VARCHAR(50) NULL,
    OtherDiabetesETerm                                     VARCHAR(200) NULL,
    OtherDiabetesEDate                                     VARCHAR(50) NULL,  
    DiabetesResolvedECode                                  VARCHAR(50) NULL,
    DiabetesResolvedETerm                                  VARCHAR(200) NULL,
    DiabetesResolvedEDate                                  VARCHAR(50) NULL,
    PancreaticDiseaseECode                                 VARCHAR(50) NULL,
    PancreaticDiseaseETerm                                 VARCHAR(200) NULL,
    PancreaticDiseaseEDate                                 VARCHAR(50) NULL,
    PancreaticSurgeryECode                                 VARCHAR(50) NULL,
    PancreaticSurgeryETerm                                 VARCHAR(200) NULL,
    PancreaticSurgeryEDate                                 VARCHAR(50) NULL,
    DiabetesInPregnancyECode                               VARCHAR(50) NULL,
    DiabetesInPregnancyETerm                               VARCHAR(200) NULL,
    DiabetesInPregnancyEDate                               VARCHAR(50) NULL,
    HyperglycaemiaInPregnancyECode                         VARCHAR(50) NULL,
    HyperglycaemiaInPregnancyETerm                         VARCHAR(200) NULL,
    HyperglycaemiaInPregnancyEDate                         VARCHAR(50) NULL,
    DiabetesEmergenciesLCode                               VARCHAR(50) NULL,
    DiabetesEmergenciesLTerm                               VARCHAR(200) NULL,
    DiabetesEmergenciesLDate                               VARCHAR(50) NULL,
    BariatricSurgeryECode                                  VARCHAR(50) NULL,
    BariatricSurgeryETerm                                  VARCHAR(200) NULL,
    BariatricSurgeryEDate                                  VARCHAR(50) NULL,
    PrediabetesECode                                       VARCHAR(50) NULL,
    PrediabetesETerm                                       VARCHAR(200) NULL,
    PrediabetesEDate                                       VARCHAR(50) NULL,
    PrediabetesLCode                                       VARCHAR(50) NULL,
    PrediabetesLTerm                                       VARCHAR(200) NULL,
    PrediabetesLDate                                       VARCHAR(50) NULL,
    AtRiskECode                                            VARCHAR(50) NULL,
    AtRiskETerm                                            VARCHAR(200) NULL,
    AtRiskEDate                                            VARCHAR(50) NULL,
    AtRiskLCode                                            VARCHAR(50) NULL,
    AtRiskLTerm                                            VARCHAR(200) NULL,
    AtRiskLDate                                            VARCHAR(50) NULL,
    HbA1cECode                                             VARCHAR(50) NULL,
    HbA1cETerm                                             VARCHAR(200) NULL,
    HbA1cEDate                                             VARCHAR(50) NULL,
    HbA1cEValue                                            VARCHAR(50) NULL,
    HbA1cEUnit                                             VARCHAR(50) NULL,
    HbA1cLCode                                             VARCHAR(50) NULL,
    HbA1cLTerm                                             VARCHAR(200) NULL,
    HbA1cLDate                                             VARCHAR(50) NULL,
    HbA1cLValue                                            VARCHAR(50) NULL,
    HbA1cLUnit                                             VARCHAR(50) NULL,
    QDiabetesECode                                         VARCHAR(50) NULL,
    QDiabetesETerm                                         VARCHAR(200) NULL,
    QDiabetesEDate                                         VARCHAR(50) NULL,
    QDiabetesEValue                                        VARCHAR(50) NULL,
    QDiabetesEUnit                                         VARCHAR(50) NULL,
    QDiabetesLCode                                         VARCHAR(50) NULL,
    QDiabetesLTerm                                         VARCHAR(200) NULL,
    QDiabetesLDate                                         VARCHAR(50) NULL,
    QDiabetesLValue                                        VARCHAR(50) NULL,
    QDiabetesLUnit                                         VARCHAR(50) NULL,
    HighQRiskECode                                         VARCHAR(50) NULL,
    HighQRiskETerm                                         VARCHAR(200) NULL,
    HighQRiskEDate                                         VARCHAR(50) NULL,
    HighQRiskEValue                                        VARCHAR(50) NULL,
    HighQRiskEUnit                                         VARCHAR(50) NULL,
    HighQRiskLCode                                         VARCHAR(50) NULL,
    HighQRiskLTerm                                         VARCHAR(200) NULL,
    HighQRiskLDate                                         VARCHAR(50) NULL,
    HighQRiskLValue                                        VARCHAR(50) NULL,
    HighQRiskLUnit                                         VARCHAR(50) NULL,
    RetinalScreenECode                                     VARCHAR(50) NULL,
    RetinalScreenETerm                                     VARCHAR(200) NULL,
    RetinalScreenEDate                                     VARCHAR(50) NULL,
    RetinalScreenLCode                                     VARCHAR(50) NULL,
    RetinalScreenLTerm                                     VARCHAR(200) NULL,
    RetinalScreenLDate                                     VARCHAR(50) NULL,
    RetinalScreenDeclinedLCode                             VARCHAR(50) NULL,
    RetinalScreenDeclinedLTerm                             VARCHAR(200) NULL,
    RetinalScreenDeclinedLDate                             VARCHAR(50) NULL,
    RetinopathyIncludeMaculopathyECode                     VARCHAR(50) NULL,
    RetinopathyIncludeMaculopathyETerm                     VARCHAR(200) NULL,
    RetinopathyIncludeMaculopathyEDate                     VARCHAR(50) NULL,
    RetinopathyIncludeMaculopathyLCode                     VARCHAR(50) NULL,
    RetinopathyIncludeMaculopathyLTerm                     VARCHAR(200) NULL,
    RetinopathyIncludeMaculopathyLDate                     VARCHAR(50) NULL,
    RetinopathyExcludeMaculopathyECode                     VARCHAR(50) NULL,
    RetinopathyExcludeMaculopathyETerm                     VARCHAR(200) NULL,
    RetinopathyExcludeMaculopathyEDate                     VARCHAR(50) NULL,
    RetinopathyExcludeMaculopathyLCode                     VARCHAR(50) NULL,
    RetinopathyExcludeMaculopathyLTerm                     VARCHAR(200) NULL,
    RetinopathyExcludeMaculopathyLDate                     VARCHAR(50) NULL,
    MaculopathyECode                                       VARCHAR(50) NULL,
    MaculopathyETerm                                       VARCHAR(200) NULL,
    MaculopathyEDate                                       VARCHAR(50) NULL,
    MaculopathyLCode                                       VARCHAR(50) NULL,
    MaculopathyLTerm                                       VARCHAR(200) NULL,
    MaculopathyLDate                                       VARCHAR(50) NULL,
    DiabeticMaculopathyECode                               VARCHAR(50) NULL,
    DiabeticMaculopathyETerm                               VARCHAR(200) NULL,
    DiabeticMaculopathyEDate                               VARCHAR(50) NULL,
    DiabeticMaculopathyLCode                               VARCHAR(50) NULL,
    DiabeticMaculopathyLTerm                               VARCHAR(200) NULL,
    DiabeticMaculopathyLDate                               VARCHAR(50) NULL,
    ErectileDysfunctionECode                               VARCHAR(50) NULL,
    ErectileDysfunctionETerm                               VARCHAR(200) NULL,
    ErectileDysfunctionEDate                               VARCHAR(50) NULL,
    PVDALLVesselsECode                                     VARCHAR(50) NULL,
    PVDALLVesselsETerm                                     VARCHAR(200) NULL,
    PVDALLVesselsEDate                                     VARCHAR(50) NULL,
    PVDVeinsECode                                          VARCHAR(50) NULL,
    PVDVeinsETerm                                          VARCHAR(200) NULL,
    PVDVeinsEDate                                          VARCHAR(50) NULL,
    PVDArteriesNoncoronaryECode                            VARCHAR(50) NULL,
    PVDArteriesNoncoronaryETerm                            VARCHAR(200) NULL,
    PVDArteriesNoncoronaryEDate                            VARCHAR(50) NULL,
    AbdominalAorticAneurysmECode                           VARCHAR(50) NULL,
    AbdominalAorticAneurysmETerm                           VARCHAR(200) NULL,
    AbdominalAorticAneurysmEDate                           VARCHAR(50) NULL,
    FootUlcerECode                                         VARCHAR(50) NULL,
    FootUlcerETerm                                         VARCHAR(200) NULL,
    FootUlcerEDate                                         VARCHAR(50) NULL,
    DiabeticFootUlcerECode                                 VARCHAR(50) NULL,
    DiabeticFootUlcerETerm                                 VARCHAR(200) NULL,
    DiabeticFootUlcerEDate                                 VARCHAR(50) NULL,
    NeuropathyECode                                        VARCHAR(50) NULL,
    NeuropathyETerm                                        VARCHAR(200) NULL,
    NeuropathyEDate                                        VARCHAR(50) NULL,
    DiabeticPeripheralNeuropathyECode                      VARCHAR(50) NULL,
    DiabeticPeripheralNeuropathyETerm                      VARCHAR(200) NULL,
    DiabeticPeripheralNeuropathyEDate                      VARCHAR(50) NULL
);
  
ALTER TABLE gh2_diagnoses1dataset ADD INDEX gh2d1_pseudoid_idx (pseudo_id);
INSERT INTO gh2_diagnoses1dataset (pseudo_id) SELECT DISTINCT group_by FROM cohort_gh2;
  
END//
DELIMITER ;