USE data_extracts;

-- ahui 5/2/2020

DROP PROCEDURE IF EXISTS createGH2Dataset1a;

DELIMITER //
CREATE PROCEDURE createGH2Dataset1a()
BEGIN

-- Demographics
-- Diagnoses (1)

DROP TABLE IF EXISTS gh2_diagnoses1adataset;

CREATE TABLE gh2_diagnoses1adataset (
    Pseudo_id                                              VARCHAR(255) NULL,
    Pseudo_NHSNumber                                       VARCHAR(255) NULL,
    CoronaryArteryDiseaseECode                             VARCHAR(50) NULL,
    CoronaryArteryDiseaseETerm                             VARCHAR(200) NULL,
    CoronaryArteryDiseaseEDate                             VARCHAR(50) NULL,
    CoronaryArteryDiseaseLCode                             VARCHAR(50) NULL,
    CoronaryArteryDiseaseLTerm                             VARCHAR(200) NULL,
    CoronaryArteryDiseaseLDate                             VARCHAR(50) NULL,
    AnginaECode                                            VARCHAR(50) NULL,
    AnginaETerm                                            VARCHAR(200) NULL,
    AnginaEDate                                            VARCHAR(50) NULL,
    MyocardialInfarctionECode                              VARCHAR(50) NULL,
    MyocardialInfarctionETerm                              VARCHAR(200) NULL,
    MyocardialInfarctionEDate                              VARCHAR(50) NULL,
    CoronaryAngioplastyECode                               VARCHAR(50) NULL,
    CoronaryAngioplastyETerm                               VARCHAR(200) NULL,
    CoronaryAngioplastyEDate                               VARCHAR(50) NULL,
    CABGECode                                              VARCHAR(50) NULL,
    CABGETerm                                              VARCHAR(200) NULL,
    CABGEDate                                              VARCHAR(50) NULL,
    AtrialFibrillationECode                                VARCHAR(50) NULL,
    AtrialFibrillationETerm                                VARCHAR(200) NULL,
    AtrialFibrillationEDate                                VARCHAR(50) NULL,
    AtrialFibrillationResolvedLCode                        VARCHAR(50) NULL,
    AtrialFibrillationResolvedLTerm                        VARCHAR(200) NULL,
    AtrialFibrillationResolvedLDate                        VARCHAR(50) NULL,
    AtrialFlutterECode                                     VARCHAR(50) NULL,
    AtrialFlutterETerm                                     VARCHAR(200) NULL,
    AtrialFlutterEDate                                     VARCHAR(50) NULL,
    HeartFailureECode                                      VARCHAR(50) NULL,
    HeartFailureETerm                                      VARCHAR(200) NULL,
    HeartFailureEDate                                      VARCHAR(50) NULL,
    TIAECode                                               VARCHAR(50) NULL,
    TIAETerm                                               VARCHAR(200) NULL,
    TIAEDate                                               VARCHAR(50) NULL,
    StrokeECode                                            VARCHAR(50) NULL,
    StrokeETerm                                            VARCHAR(200) NULL,
    StrokeEDate                                            VARCHAR(50) NULL,
    HypertensionECode                                      VARCHAR(50) NULL,
    HypertensionETerm                                      VARCHAR(200) NULL,
    HypertensionEDate                                      VARCHAR(50) NULL,
    EssentialHypertensionECode                             VARCHAR(50) NULL,
    EssentialHypertensionETerm                             VARCHAR(200) NULL,
    EssentialHypertensionEDate                             VARCHAR(50) NULL,
    SecondaryHypertensionECode                             VARCHAR(50) NULL,
    SecondaryHypertensionETerm                             VARCHAR(200) NULL,
    SecondaryHypertensionEDate                             VARCHAR(50) NULL,
    ResistantHypertensionECode                             VARCHAR(50) NULL,
    ResistantHypertensionETerm                             VARCHAR(200) NULL,
    ResistantHypertensionEDate                             VARCHAR(50) NULL,
    HypertensionResolvedLCode                              VARCHAR(50) NULL,
    HypertensionResolvedLTerm                              VARCHAR(200) NULL,
    HypertensionResolvedLDate                              VARCHAR(50) NULL,
    ChronicKidneyDiseaseECode                              VARCHAR(50) NULL,
    ChronicKidneyDiseaseETerm                              VARCHAR(200) NULL,
    ChronicKidneyDiseaseEDate                              VARCHAR(50) NULL,
    ChronicKidneyDiseaseLCode                              VARCHAR(50) NULL,
    ChronicKidneyDiseaseLTerm                              VARCHAR(200) NULL,
    ChronicKidneyDiseaseLDate                              VARCHAR(50) NULL,
    DialysisECode                                          VARCHAR(50) NULL,
    DialysisETerm                                          VARCHAR(200) NULL,
    DialysisEDate                                          VARCHAR(50) NULL,
    DialysisLCode                                          VARCHAR(50) NULL,
    DialysisLTerm                                          VARCHAR(200) NULL,
    DialysisLDate                                          VARCHAR(50) NULL,
    RenalTransplantationECode                              VARCHAR(50) NULL,
    RenalTransplantationETerm                              VARCHAR(200) NULL,
    RenalTransplantationEDate                              VARCHAR(50) NULL,
    RenalTransplantationLCode                              VARCHAR(50) NULL,
    RenalTransplantationLTerm                              VARCHAR(200) NULL,
    RenalTransplantationLDate                              VARCHAR(50) NULL,
    RenalTransplantRejectionECode                          VARCHAR(50) NULL,
    RenalTransplantRejectionETerm                          VARCHAR(200) NULL,
    RenalTransplantRejectionEDate                          VARCHAR(50) NULL,
    RenalTransplantRejectionLCode                          VARCHAR(50) NULL,
    RenalTransplantRejectionLTerm                          VARCHAR(200) NULL,
    RenalTransplantRejectionLDate                          VARCHAR(50) NULL,
    PolycysticOvarianSyndromeECode                         VARCHAR(50) NULL,
    PolycysticOvarianSyndromeETerm                         VARCHAR(200) NULL,
    PolycysticOvarianSyndromeEDate                         VARCHAR(50) NULL,
    SleepDisorderedBreathingECode                          VARCHAR(50) NULL,
    SleepDisorderedBreathingETerm                          VARCHAR(200) NULL,
    SleepDisorderedBreathingEDate                          VARCHAR(50) NULL,
    ObesityRelatedBreathingDisordersECode                  VARCHAR(50) NULL,
    ObesityRelatedBreathingDisordersETerm                  VARCHAR(200) NULL,
    ObesityRelatedBreathingDisordersEDate                  VARCHAR(50) NULL, 
    NAFLDECode                                             VARCHAR(50) NULL,
    NAFLDETerm                                             VARCHAR(200) NULL,
    NAFLDEDate                                             VARCHAR(50) NULL,
    FamilialHypercholesterolaemiaECode                     VARCHAR(50) NULL,
    FamilialHypercholesterolaemiaETerm                     VARCHAR(200) NULL,
    FamilialHypercholesterolaemiaEDate                     VARCHAR(50) NULL,
    AcanthosisNigricansECode                               VARCHAR(50) NULL,
    AcanthosisNigricansETerm                               VARCHAR(200) NULL,
    AcanthosisNigricansEDate                               VARCHAR(50) NULL,
    HyperthyroidismECode                                   VARCHAR(50) NULL, 
    HyperthyroidismETerm                                   VARCHAR(200) NULL,
    HyperthyroidismEDate                                   VARCHAR(50) NULL,
    HyperthyroidismLCode                                   VARCHAR(50) NULL, 
    HyperthyroidismLTerm                                   VARCHAR(200) NULL,
    HyperthyroidismLDate                                   VARCHAR(50) NULL,
    GravesDiseaseECode                                     VARCHAR(50) NULL,
    GravesDiseaseETerm                                     VARCHAR(200) NULL,
    GravesDiseaseEDate                                     VARCHAR(50) NULL,
    ToxicMultinodularGoitreECode                           VARCHAR(50) NULL,
    ToxicMultinodularGoitreETerm                           VARCHAR(200) NULL,
    ToxicMultinodularGoitreEDate                           VARCHAR(50) NULL,
    ToxicThyroidAdenomaECode                               VARCHAR(50) NULL,
    ToxicThyroidAdenomaETerm                               VARCHAR(200) NULL,
    ToxicThyroidAdenomaEDate                               VARCHAR(50) NULL,
    HypothyroidismECode                                    VARCHAR(50) NULL,
    HypothyroidismETerm                                    VARCHAR(200) NULL,
    HypothyroidismEDate                                    VARCHAR(50) NULL,
    HypothyroidismLCode                                    VARCHAR(50) NULL,
    HypothyroidismLTerm                                    VARCHAR(200) NULL,
    HypothyroidismLDate                                    VARCHAR(50) NULL,
    PrimaryHypothroidismExcSecSubECode                     VARCHAR(50) NULL,
    PrimaryHypothroidismExcSecSubETerm                     VARCHAR(200) NULL,
    PrimaryHypothroidismExcSecSubEDate                     VARCHAR(50) NULL,
    AutoimmuneHypothyroidismECode                          VARCHAR(50) NULL,
    AutoimmuneHypothyroidismETerm                          VARCHAR(200) NULL,
    AutoimmuneHypothyroidismEDate                          VARCHAR(50) NULL,
    HashimotosThyroiditisECode                             VARCHAR(50) NULL,
    HashimotosThyroiditisETerm                             VARCHAR(200) NULL,
    HashimotosThyroiditisEDate                             VARCHAR(50) NULL,
    CoeliacDiseaseECode                                    VARCHAR(50) NULL,
    CoeliacDiseaseETerm                                    VARCHAR(200) NULL,
    CoeliacDiseaseEDate                                    VARCHAR(50) NULL,
    VitiligoECode                                          VARCHAR(50) NULL,
    VitiligoETerm                                          VARCHAR(200) NULL,
    VitiligoEDate                                          VARCHAR(50) NULL, 
    FrailtyIndexLCode                                      VARCHAR(50) NULL,
    FrailtyIndexLTerm                                      VARCHAR(200) NULL,
    FrailtyIndexLDate                                      VARCHAR(50) NULL, 
    NHSHealthCheckLCode                                    VARCHAR(50) NULL, 
    NHSHealthCheckLTerm                                    VARCHAR(200) NULL,
    NHSHealthCheckLDate                                    VARCHAR(50) NULL,
    MetforminAdverseReactionECode                          VARCHAR(50) NULL,
    MetforminAdverseReactionETerm                          VARCHAR(200) NULL,
    MetforminAdverseReactionEDate                          VARCHAR(50) NULL,
    StatinAdverseReactionsDisorderECode                    VARCHAR(50) NULL,
    StatinAdverseReactionsDisorderETerm                    VARCHAR(200) NULL,
    StatinAdverseReactionsDisorderEDate                    VARCHAR(50) NULL,
    StatinAdverseReactionsSituationECode                   VARCHAR(50) NULL,
    StatinAdverseReactionsSituationETerm                   VARCHAR(200) NULL,
    StatinAdverseReactionsSituationEDate                   VARCHAR(50) NULL,
    StatinMuscleSymptomsDisorderECode                      VARCHAR(50) NULL,
    StatinMuscleSymptomsDisorderETerm                      VARCHAR(200) NULL,
    StatinMuscleSymptomsDisorderEDate                      VARCHAR(50) NULL,
    StatinMuscleSymptomsFindingECode                       VARCHAR(50) NULL,
    StatinMuscleSymptomsFindingETerm                       VARCHAR(200) NULL,
    StatinMuscleSymptomsFindingEDate                       VARCHAR(50) NULL
);
  
ALTER TABLE gh2_diagnoses1adataset ADD INDEX gh2d1a_pseudoid_idx (pseudo_id);
INSERT INTO gh2_diagnoses1adataset (pseudo_id) SELECT DISTINCT group_by FROM cohort_gh2;
  
END//
DELIMITER ;