insert into code_set (id, name) values (59, 'ELGH Coeliac disease');
insert into code_set (id, name) values (60, 'ELGH Vitiligo');
insert into code_set (id, name) values (61, 'ELGH RTR');
insert into code_set (id, name) values (62, 'ELGH RT');
insert into code_set (id, name) values (63, 'ELGH Dialysis');
insert into code_set (id, name) values (64, 'ELGh Stroke (ischaemic)');
insert into code_set (id, name) values (65, 'ELGh Stroke (haemorrhagic)');
insert into code_set (id, name) values (66, 'ELGH TIA');
insert into code_set (id, name) values (67, 'ELGH Angina');
insert into code_set (id, name) values (68, 'ELGH Myocardial Infarction');
insert into code_set (id, name) values (69, 'ELGH Ethnicity');
insert into code_set (id, name) values (70, 'ELGH Country of Birth');
insert into code_set (id, name) values (71, 'ELGH Family History of diabetes');
insert into code_set (id, name) values (72, 'ELGH Family History of ICD');
insert into code_set (id, name) values (73, 'ELGH Type 1 Diabetes');
insert into code_set (id, name) values (74, 'ELGH Type 2 diabetes');
insert into code_set (id, name) values (75, 'ELGH secondary diabetes');
insert into code_set (id, name) values (76, 'ELGH other diabetes');
insert into code_set (id, name) values (77, 'ELGH pancreatic disease');
insert into code_set (id, name) values (78, 'ELGH Diabeties in pregnancy');
insert into code_set (id, name) values (79, 'ELGH Diabetes emergencies');
insert into code_set (id, name) values (80, 'ELGH Bariatric surgery');
insert into code_set (id, name) values (81, 'ELGH diabetes risk 1');
insert into code_set (id, name) values (82, 'ELGH diabetes risk 2');
insert into code_set (id, name) values (83, 'ELGH diabetes risk 3');
insert into code_set (id, name) values (84, 'ELGH diabetes risk 4');
insert into code_set (id, name) values (85, 'ELGH cvd risk');
insert into code_set (id, name) values (86, 'ELGH Retinopathy Screen');
insert into code_set (id, name) values (87, 'ELGH Retinopathy Left');
insert into code_set (id, name) values (88, 'ELGH No Retinopathy Left');
insert into code_set (id, name) values (89, 'ELGH Retinopathy Right');
insert into code_set (id, name) values (90, 'ELGH No Retinopathy Right');
insert into code_set (id, name) values (91, 'ELGH ED');
insert into code_set (id, name) values (92, 'ELGH PVD');
insert into code_set (id, name) values (93, 'ELGH PAD');
insert into code_set (id, name) values (94, 'ELGH AAA');
insert into code_set (id, name) values (95, 'ELGH Foot Ulcer Left');
insert into code_set (id, name) values (96, 'ELGH Foot Ulcer Right');
insert into code_set (id, name) values (97, 'ELGH Neuropathy');
insert into code_set (id, name) values (98, 'ELGH IHD');
insert into code_set (id, name) values (99, 'ELGH AF Flutter');
insert into code_set (id, name) values (100, 'ELGH HD');
insert into code_set (id, name) values (101, 'ELGH Stroke');
insert into code_set (id, name) values (102, 'ELGH Hypertension');
insert into code_set (id, name) values (103, 'ELGH CKD');
insert into code_set (id, name) values (104, 'ELGH PCS');
insert into code_set (id, name) values (105, 'ELGH Obesity Disorder');
insert into code_set (id, name) values (106, 'ELGH NAFLD');
insert into code_set (id, name) values (107, 'ELGH Hypercholesterol');
insert into code_set (id, name) values (108, 'ELGH Acanthosis');
insert into code_set (id, name) values (109, 'ELGH Thyroid');
insert into code_set (id, name) values (110, 'ELGH Autoimmune');
insert into code_set (id, name) values (111, 'ELGH Frailtyindex');
insert into code_set (id, name) values (112, 'ELGH NHS HC');
insert into code_set (id, name) values (113, 'ELGH Asthma');
insert into code_set (id, name) values (114, 'ELGH COPD');
insert into code_set (id, name) values (115, 'ELGH IPF');
insert into code_set (id, name) values (116, 'ELGH AMD');
insert into code_set (id, name) values (117, 'ELGH Glaucoma');
insert into code_set (id, name) values (118, 'ELGH RA');
insert into code_set (id, name) values (119, 'ELGH Lupus');
insert into code_set (id, name) values (120, 'ELGH Crohns');
insert into code_set (id, name) values (121, 'ELGH UC');
insert into code_set (id, name) values (122, 'ELGH Eczema');
insert into code_set (id, name) values (123, 'ELGH PCD');
insert into code_set (id, name) values (124, 'ELGH MND');
insert into code_set (id, name) values (125, 'ELGH MS');
insert into code_set (id, name) values (126, 'ELGH Parkinsons');
insert into code_set (id, name) values (127, 'ELGH Atypical PD');
insert into code_set (id, name) values (128, 'ELGH VasDem');
insert into code_set (id, name) values (129, 'ELGH Alzheimers');
insert into code_set (id, name) values (130, 'ELGH DementiaQOF');
insert into code_set (id, name) values (131, 'ELGH Cognitive');
insert into code_set (id, name) values (132, 'ELGH Memory');
insert into code_set (id, name) values (133, 'ELGH Brain tumour');
insert into code_set (id, name) values (134, 'ELGH Brain damage');
insert into code_set (id, name) values (135, 'ELGH Epilepsy');
insert into code_set (id, name) values (136, 'ELGH Schizophrenic');
insert into code_set (id, name) values (137, 'ELGH Bipolar');
insert into code_set (id, name) values (138, 'ELGH Depression');
insert into code_set (id, name) values (139, 'ELGH Anxiety');
insert into code_set (id, name) values (140, 'ELGH PTSD');
insert into code_set (id, name) values (141, 'ELGH OCD');
insert into code_set (id, name) values (142, 'ELGH Panic');
insert into code_set (id, name) values (143, 'ELGH Social anxiety');
insert into code_set (id, name) values (144, 'ELGH Phobias');
insert into code_set (id, name) values (145, 'ELGH SAD');
insert into code_set (id, name) values (146, 'ELGH Conversion');
insert into code_set (id, name) values (147, 'ELGH Adjustment');
insert into code_set (id, name) values (148, 'ELGH Somatoform');
insert into code_set (id, name) values (149, 'ELGH Eating disorder');
insert into code_set (id, name) values (150, 'ELGH Dependence and abuse');
insert into code_set (id, name) values (151, 'ELGH ADHD');
insert into code_set (id, name) values (152, 'ELGH Personality');
insert into code_set (id, name) values (153, 'ELGH Habit');
insert into code_set (id, name) values (154, 'ELGH LD');
insert into code_set (id, name) values (155, 'ELGH Autism');
insert into code_set (id, name) values (156, 'ELGH Speech and language');
insert into code_set (id, name) values (157, 'ELGH Conduct');
insert into code_set (id, name) values (158, 'ELGH Tourettes');
insert into code_set (id, name) values (159, 'ELGH Gender');
insert into code_set (id, name) values (160, 'ELGH Smoker');
insert into code_set (id, name) values (161, 'ELGH ExSmoker');
insert into code_set (id, name) values (162, 'ELGH NeverSmoked');
insert into code_set (id, name) values (163, 'ELGH Weight');
insert into code_set (id, name) values (164, 'ELGH Height');
insert into code_set (id, name) values (165, 'ELGH BMI');
insert into code_set (id, name) values (166, 'ELGH HbA1c');
insert into code_set (id, name) values (167, 'ELGH Cholesterol');
insert into code_set (id, name) values (168, 'ELGH HDL');
insert into code_set (id, name) values (169, 'ELGH LDL');
insert into code_set (id, name) values (170, 'ELGH Triglycerides');
insert into code_set (id, name) values (171, 'ELGH Protein Creatinine');
insert into code_set (id, name) values (172, 'ELGH Albumin Creatinine');
insert into code_set (id, name) values (173, 'ELGH Albumin');
insert into code_set (id, name) values (174, 'ELGH Sys BP');
insert into code_set (id, name) values (175, 'ELGH Dia BP');
insert into code_set (id, name) values (176, 'ELGH Creatinine');
insert into code_set (id, name) values (177, 'ELGH EGFR');
insert into code_set (id, name) values (178, 'ELGH GAD');
insert into code_set (id, name) values (179, 'ELGH Islet cell');
insert into code_set (id, name) values (180, 'ELGH IA2');
insert into code_set (id, name) values (181, 'ELGH Coeliac autoantibody');
insert into code_set (id, name) values (182, 'ELGH Peroxidase');
insert into code_set (id, name) values (183, 'ELGH Cpeptide');
insert into code_set (id, name) values (184, 'ELGH Serum insulin');
insert into code_set (id, name) values (185, 'ELGH Serum ALT');
insert into code_set (id, name) values (186, 'ELGH AST serum');
insert into code_set (id, name) values (187, 'ELGH TSH, T4');
insert into code_set (id, name) values (189, 'ELGH Type 1 & T2 Diabetes');
