USE data_extracts;

DROP PROCEDURE IF EXISTS populateELCCGCodes;

DELIMITER //

CREATE PROCEDURE populateELCCGCodes()
BEGIN

INSERT INTO elccg_codes (NAME,LOCAL_ID,PARENT,PUBLISHER_CONFIG)
VALUES
('Allerton Road Medical Centre','F84716','City & Hackney CCG','publisher_01'),
('Athena Medical Centre','F84060','City & Hackney CCG','publisher_02'),
('Barretts Grove Surgery','F84636','City & Hackney CCG','publisher_01'),
('Barton House Group Practice','F84008','City & Hackney CCG','publisher_02'),
('BEECHWOOD MEDICAL CENTRE','F84038','City & Hackney CCG','publisher_02'),
('Cranwich Road Surgery','F84686','City & Hackney CCG','publisher_02'),
('De Beauvoir Surgery','F84072','City & Hackney CCG','publisher_01'),
('Dr Tahalani and Partners','F84041','City & Hackney CCG','publisher_01'),
('Elm Practice','F84685','City & Hackney CCG','publisher_01'),
('Elsdale Street Surgery','F84601','City & Hackney CCG','publisher_02'),
('GADHVI PRACTICE','F84080','City & Hackney CCG','publisher_02'),
('Greenhouse','F84632','City & Hackney CCG','publisher_01'),
('HEALY MEDICAL CENTRE','F84720','City & Hackney CCG','publisher_03'),
('KINGSMEAD HEALTHCARE','F84015','City & Hackney CCG','publisher_03'),
('Latimer Health Centre','F84719','City & Hackney CCG','publisher_02'),
('London Fields Medical Centre','F84021','City & Hackney CCG','publisher_03'),
('Lower Clapton Group Practice','F84003','City & Hackney CCG','publisher_01'),
('Nightingale Practice','F84018','City & Hackney CCG','publisher_03'),
('Queensbridge Group Practice','F84117','City & Hackney CCG','publisher_01'),
('Richmond Road Medical Centre','F84035','City & Hackney CCG','publisher_03'),
('Rosewood Practice','F84711','City & Hackney CCG','publisher_03'),
('Sandringham Practice','F84621','City & Hackney CCG','publisher_01'),
('Shoreditch Park Surgery','F84635','City & Hackney CCG','publisher_02'),
('Somerford Grove Practice','F84033','City & Hackney CCG','publisher_01'),
('Spring Hill Practice','Y03049','City & Hackney CCG','publisher_03'),
('Stamford Hill Group Practice','F84013','City & Hackney CCG','publisher_02'),
('The Cedar Practice','F84036','City & Hackney CCG','publisher_02'),
('The Clapton Surgery','F84668','City & Hackney CCG','publisher_03'),
('The Dalston Practice','F84063','City & Hackney CCG','publisher_03'),
('The Heron Practice','F84119','City & Hackney CCG','publisher_01'),
('THE HOXTON SURGERY','F84692','City & Hackney CCG','publisher_02'),
('The Lawson Practice','F84096','City & Hackney CCG','publisher_03'),
('The Lea Surgery','F84105','City & Hackney CCG','publisher_03'),
('The Neaman Practice','F84640','City & Hackney CCG','publisher_02'),
('The Riverside Practice','F84619','City & Hackney CCG','publisher_01'),
('The Statham Grove Surgery','F84115','City & Hackney CCG','publisher_03'),
('The Surgery (Brooke Road)','F84694','City & Hackney CCG','publisher_03'),
('The Wick Health Centre','F84620','City & Hackney CCG','publisher_02'),
('Trowbridge Surgery','Y00403','City & Hackney CCG','publisher_03'),
('Well Street Surgery','F84069','City & Hackney CCG','publisher_03'),
('Abbey Road Medical Practice','F84111','Newham CCG','publisher_01'),
('Albert Road Surgery','Y02928','Newham CCG','publisher_01'),
('BALAAM STREET PRACTICE','F84681','Newham CCG','publisher_02'),
('Birchdale Road Medical Centre','F84641','Newham CCG','publisher_01'),
('BOLEYN MEDICAL CENTRE','F84050','Newham CCG','publisher_02'),
('Boleyn Road Practice','F84734','Newham CCG','publisher_02'),
('Claremont Clinic','F84097','Newham CCG','publisher_01'),
('Cumberland Medical Centre','F84657','Newham CCG','publisher_02'),
('CUSTOM HOUSE SURGERY','F84047','Newham CCG','publisher_01'),
('Dr Bhadra''S Surgery','F84729','Newham CCG','publisher_01'),
('DR CM PATEL''S SURGERY','F84660','Newham CCG','publisher_02'),
('DR N DRIVER AND PARTNERS','F84086','Newham CCG','publisher_02'),
('DR PCL KNIGHT','F84730','Newham CCG','publisher_01'),
('DR PI ABIOLA','F84631','Newham CCG','publisher_02'),
('Dr R Samuel & Partner','F84077','Newham CCG','publisher_02'),
('DR SKS SWEDAN','F84706','Newham CCG','publisher_03'),
('DR T KRISHNAMURTHY','F84741','Newham CCG','publisher_02'),
('DR T LWIN','F84708','Newham CCG','publisher_02'),
('E12 HEALTH','F84121','Newham CCG','publisher_01'),
('E12 MEDICAL CENTRE','F84739','Newham CCG','publisher_02'),
('EAST END MEDICAL CENTRE','F84677','Newham CCG','publisher_02'),
('ESSEX LODGE','F84052','Newham CCG','publisher_02'),
('Glen Road Medical Centre','F84092','Newham CCG','publisher_03'),
('GREENGATE MEDICAL CENTRE','F84053','Newham CCG','publisher_01'),
('LANTERN HEALTH-CARPENTERS PRACTICE','F84749','Newham CCG','publisher_02'),
('Lathom Road Medical Centre','F84070','Newham CCG','publisher_03'),
('Leytonstone Road Medical Centre','F84672','Newham CCG','publisher_03'),
('Lucas Avenue Practice','F84642','Newham CCG','publisher_03'),
('MARKET STREET HEALTH GROUP','F84004','Newham CCG','publisher_03'),
('NEWHAM MEDICAL CENTRE','F84669','Newham CCG','publisher_02'),
('NEWHAM TRANSITIONAL PRACTICE','F84740','Newham CCG','publisher_03'),
('Plashet Medical Centre','F84088','Newham CCG','publisher_01'),
('Royal Docks Medical Practice','F84717','Newham CCG','publisher_03'),
('SANGAM SURGERY','F84658','Newham CCG','publisher_01'),
('Shrewsbury Road Surgery','F84006','Newham CCG','publisher_03'),
('Sir Ludwig Guttmann Health Centre','Y04273','Newham CCG','publisher_01'),
('St Luke''S Medical Centre','F84666','Newham CCG','publisher_02'),
('ST. BARTHOLOMEWS SURGERY','F84010','Newham CCG','publisher_03'),
('Star Lane Medical Centre','F84017','Newham CCG','publisher_01'),
('STRATFORD HEALTH CENTRE','F84022','Newham CCG','publisher_02'),
('Stratford Village Surgery','F84009','Newham CCG','publisher_01'),
('The Azad Practice','F84735','Newham CCG','publisher_02'),
('The Project Surgery','F84124','Newham CCG','publisher_03'),
('THE SUMMIT PRACTICE','F84742','Newham CCG','publisher_01'),
('The Upton Lane Medical Centre','F84014','Newham CCG','publisher_03'),
('The Westbury Road Medical Practice','F84670','Newham CCG','publisher_03'),
('TOLLGATE MEDICAL CENTRE','F84093','Newham CCG','publisher_03'),
('Venugopal RS','F84673','Newham CCG','publisher_03'),
('Woodgrange Medical Practice','F84724','Newham CCG','publisher_03'),
('Wordsworth Health Centre','F84074','Newham CCG','publisher_01'),
('Aberfeldy Practice','F84698','Tower Hamlets CCG','publisher_01'),
('ALBION HEALTH CENTRE','F84012','Tower Hamlets CCG','publisher_01'),
('Bethnal Green Health Centre','F84083','Tower Hamlets CCG','publisher_01'),
('Brayford Square Surgery','F84046','Tower Hamlets CCG','publisher_02'),
('Chrisp Street Health Centre','F84062','Tower Hamlets CCG','publisher_02'),
('CITY WELLBEING PRACTICE','F84114','Tower Hamlets CCG','publisher_02'),
('DOCKLANDS MEDICAL CENTRE','F84656','Tower Hamlets CCG','publisher_02'),
('EAST ONE HEALTH','F84682','Tower Hamlets CCG','publisher_02'),
('Globe Town Surgery','F84123','Tower Hamlets CCG','publisher_01'),
('Gough Walk Practice','F84025','Tower Hamlets CCG','publisher_02'),
('Harford Health Centre','F84087','Tower Hamlets CCG','publisher_01'),
('HARLEY GROVE MEDICAL CTR.','F84044','Tower Hamlets CCG','publisher_02'),
('Health E1','F84733','Tower Hamlets CCG','publisher_02'),
('ISLAND HEALTH','F84710','Tower Hamlets CCG','publisher_03'),
('JUBILEE STREET PRACTICE','F84031','Tower Hamlets CCG','publisher_03'),
('Merchant Street Surgery','F84118','Tower Hamlets CCG','publisher_02'),
('Pollard Row Practice APMS','Y00212','Tower Hamlets CCG','publisher_03'),
('ROSERTON STREET SURGERY','F84647','Tower Hamlets CCG','publisher_03'),
('Ruston Street Clinic','F84030','Tower Hamlets CCG','publisher_03'),
('St Andrews Health Centre','Y03023','Tower Hamlets CCG','publisher_01'),
('St Pauls Way Medical Centre','F84714','Tower Hamlets CCG','publisher_01'),
('St Stephen''S Health Centre','F84034','Tower Hamlets CCG','publisher_03'),
('ST. KATHERINE''S DOCK PRACTICE','F84731','Tower Hamlets CCG','publisher_03'),
('Stroudley Walk Health Centre','F84676','Tower Hamlets CCG','publisher_02'),
('STROUTS PLACE MEDICAL CENTRE','F84051','Tower Hamlets CCG','publisher_02'),
('THE BARKANTINE PRACTICE','F84747','Tower Hamlets CCG','publisher_03'),
('The Blithehale Medical Centre','F84718','Tower Hamlets CCG','publisher_03'),
('The Grove Road Surgery','F84055','Tower Hamlets CCG','publisher_01'),
('The Limehouse Practice','F84054','Tower Hamlets CCG','publisher_02'),
('The Mission Practice','F84016','Tower Hamlets CCG','publisher_03'),
('THE SPITALFIELDS PRACTICE','F84081','Tower Hamlets CCG','publisher_02'),
('The Tredegar Practice','F84696','Tower Hamlets CCG','publisher_03'),
('THE WAPPING GROUP PRACTICE','F84079','Tower Hamlets CCG','publisher_03'),
('Whitechapel Health Centre','F84039','Tower Hamlets CCG','publisher_03'),
('XX Place Surgery','F84122','Tower Hamlets CCG','publisher_03'),
('Addison Road Medical Practice','F86607','Waltham Forest CCG',''),
('Chingford Medical Practice','Y01291','Waltham Forest CCG',''),
('CHURCHILL MEDICAL CENTRE','F86627','Waltham Forest CCG',''),
('Claremont Medical Centre','F86708','Waltham Forest CCG',''),
('Crawley Road Medical Centre','F86044','Waltham Forest CCG',''),
('Dr Dhital Practice','F86086','Waltham Forest CCG',''),
('Dr Mohamed Green Man Medical Centre','F86621','Waltham Forest CCG',''),
('Dr Shantir Practice','F86626','Waltham Forest CCG',''),
('Francis Road Medical Centre','F86696','Waltham Forest CCG',''),
('Hampton Medical Practice','F86712','Waltham Forest CCG',''),
('Harrow Road GP Practice','F86666','Waltham Forest CCG',''),
('High Road Surgery','F86045','Waltham Forest CCG',''),
('Higham Hill Medical Centre','F86679','Waltham Forest CCG',''),
('KINGS HEAD MEDICAL PRACTICE','F86700','Waltham Forest CCG',''),
('Kiyani Medical Practice','F86701','Waltham Forest CCG',''),
('Langthorne Health Centre','F86625','Waltham Forest CCG',''),
('Langthorne Sharma Family Practice','F86705','Waltham Forest CCG',''),
('Larkshall Medical Centre','F86664','Waltham Forest CCG',''),
('Lime Tree Surgery','F86650','Waltham Forest CCG',''),
('Orient Practice','Y02585','Waltham Forest CCG',''),
('Queens Road Medical Centre','F86030','Waltham Forest CCG',''),
('Seymour Medical Centre','F86006','Waltham Forest CCG',''),
('Sinnott Road Surgery','Y01839','Waltham Forest CCG',''),
('SMA Medical Practice','F86038','Waltham Forest CCG',''),
('The Allum Medical Centre','F86036','Waltham Forest CCG',''),
('The Bailey Practice','F86689','Waltham Forest CCG',''),
('The Firs','F86001','Waltham Forest CCG',''),
('The Grove Medical Centre','F86062','Waltham Forest CCG',''),
('The Lyndhurst Surgery','F86088','Waltham Forest CCG',''),
('The Manor Practice','F86011','Waltham Forest CCG',''),
('The Old Church Surgery','F86616','Waltham Forest CCG',''),
('The Penrhyn Surgery','F86005','Waltham Forest CCG',''),
('The Ridgeway Surgery','F86078','Waltham Forest CCG',''),
('The St James Practice','F86058','Waltham Forest CCG',''),
('WALTHAM FOREST COMM & FAM HTH SERV LTD','F86644','Waltham Forest CCG',''),
('Handsworth Medical Practice','F86004','Waltham Forest CCG',''),
('LEYTON HEALTHCARE 4TH FLOOR','F86074','Waltham Forest CCG',''),
('THE ECCLESBOURNE PRACTICE','F86018','Waltham Forest CCG',''),
('THE FOREST SURGERY','F86026','Waltham Forest CCG',''),
('The Microfaculty','F86638','Waltham Forest CCG',''),
('ABBEY MEDICAL CENTRE','F82625','NHS BARKING AND DAGENHAM CCG',''),
('BARKING MEDICAL GROUP PRACTICE','F82018','NHS BARKING AND DAGENHAM CCG',''),
('DR A MOGHAL''S PRACTICE','F82677','NHS BARKING AND DAGENHAM CCG',''),
('DR AA ANSARI''S PRACTICE','F82650','NHS BARKING AND DAGENHAM CCG',''),
('DR BK JAISWAL''S PRACTICE','F82025','NHS BARKING AND DAGENHAM CCG',''),
('DR C OLA''S PRACTICE','F82621','NHS BARKING AND DAGENHAM CCG',''),
('DR DP SHAH''S PRACTICE','F82679','NHS BARKING AND DAGENHAM CCG',''),
('DR GS KALKAT''S PRACTICE','F82676','NHS BARKING AND DAGENHAM CCG',''),
('DR KM ALKAISY PRACTICE','F82678','NHS BARKING AND DAGENHAM CCG',''),
('DR M EHSAN','Y01795','NHS BARKING AND DAGENHAM CCG',''),
('DR M FATEH''S PRACTICE','F82003','NHS BARKING AND DAGENHAM CCG',''),
('DR M GOYAL''S PRACTICE','F82005','NHS BARKING AND DAGENHAM CCG',''),
('DR P PRASAD''S PRACTICE','F82027','NHS BARKING AND DAGENHAM CCG',''),
('DR R CHIBBER''S PRACTICE','F82647','NHS BARKING AND DAGENHAM CCG',''),
('DR SN AHMAD''S PRACTICE','F82015','NHS BARKING AND DAGENHAM CCG',''),
('DR SZ HAIDER''S PRACTICE','F82038','NHS BARKING AND DAGENHAM CCG',''),
('DR UA AFSER''S PRACTICE','F86040','NHS BARKING AND DAGENHAM CCG',''),
('FIVE ELMS MEDICAL PRACTICE','F82012','NHS BARKING AND DAGENHAM CCG',''),
('GABLES SURGERY','F82642','NHS BARKING AND DAGENHAM CCG',''),
('GREEN LANE SURGERY','F82661','NHS BARKING AND DAGENHAM CCG',''),
('HALBUTT STREET SURGERY','F82001','NHS BARKING AND DAGENHAM CCG',''),
('HEATHWAY MEDICAL CENTRE','F82634','NHS BARKING AND DAGENHAM CCG',''),
('HIGHGROVE SURGERY','F82680','NHS BARKING AND DAGENHAM CCG',''),
('JOHN SMITH MEDICAL CENTRE','F82040','NHS BARKING AND DAGENHAM CCG',''),
('KING EDWARDS MEDICAL CENTRE','F82042','NHS BARKING AND DAGENHAM CCG',''),
('LABURNUM HEALTH CENTRE','F82051','NHS BARKING AND DAGENHAM CCG',''),
('MARKS GATE HEALTH CENTRE','F82604','NHS BARKING AND DAGENHAM CCG',''),
('PORTERS AVENUE HEALTH CENTRE','Y02575','NHS BARKING AND DAGENHAM CCG',''),
('PRIME PRACTICE PARTNERSHIP','Y01719','NHS BARKING AND DAGENHAM CCG',''),
('SHIFA MEDICAL PRACTICE','Y01280','NHS BARKING AND DAGENHAM CCG',''),
('ST ALBANS SURGERY','F82017','NHS BARKING AND DAGENHAM CCG',''),
('THE WHITE HOUSE SURGERY','F82612','NHS BARKING AND DAGENHAM CCG',''),
('TULASI MEDICAL CENTRE','F82660','NHS BARKING AND DAGENHAM CCG',''),
('VICTORIA MEDICAL CENTRE','F82034','NHS BARKING AND DAGENHAM CCG',''),
('BERWICK SURGERY','F82649','NHS HAVERING CCG',''),
('BILLET LANE MEDICAL PRACTICE','F82675','NHS HAVERING CCG',''),
('CENTRAL PARK SURGERY','F82016','NHS HAVERING CCG',''),
('CHASE CROSS MEDICAL CENTRE','F82630','NHS HAVERING CCG',''),
('CHOWDHURY','F82045','NHS HAVERING CCG',''),
('CRANHAM HEALTH CENTRE','F82674','NHS HAVERING CCG',''),
('DR A PATEL','F82686','NHS HAVERING CCG',''),
('DR ABDULLAH','F82627','NHS HAVERING CCG',''),
('DR C DAHS & DR IP HUMBERSTONE SURGERY','F82006','NHS HAVERING CCG',''),
('DR GUPTA','F82610','NHS HAVERING CCG',''),
('DR HAMILTON-SMITH','F82019','NHS HAVERING CCG',''),
('DR JOSEPH','F82639','NHS HAVERING CCG',''),
('DR MARKS PRACTICE','F82663','NHS HAVERING CCG',''),
('DR P & S POOLOGANATHAN','F82039','NHS HAVERING CCG',''),
('DR PM PATEL','F82609','NHS HAVERING CCG',''),
('DR SANOMI','F82031','NHS HAVERING CCG',''),
('DR VM PATEL','F82033','NHS HAVERING CCG',''),
('HAIDERIAN MEDICAL CENTRE','F82002','NHS HAVERING CCG',''),
('HARLOW ROAD SURGERY','F82619','NHS HAVERING CCG',''),
('HIGH STREET SURGERY','F82023','NHS HAVERING CCG',''),
('HORNCHURCH HEALTHCARE','F82055','NHS HAVERING CCG',''),
('INGREBOURNE MEDICAL CENTRE','F82648','NHS HAVERING CCG',''),
('JABBAR','F82670','NHS HAVERING CCG',''),
('KINGS PARK SURGERY','Y02973','NHS HAVERING CCG',''),
('KUCCHAI','F82014','NHS HAVERING CCG',''),
('LYNWOOD MEDICAL CENTRE','F82030','NHS HAVERING CCG',''),
('MAWNEY MEDICAL CENTRE','F82011','NHS HAVERING CCG',''),
('MAYLANDS HEALTH CARE','F82008','NHS HAVERING CCG',''),
('MODERN MEDICAL CENTRE','F82638','NHS HAVERING CCG',''),
('MUNGO PARK SURGERY','F82614','NHS HAVERING CCG',''),
('NORTH STREET MEDICAL CARE','F82009','NHS HAVERING CCG',''),
('PETERSFIELD SURGERY','F82010','NHS HAVERING CCG',''),
('PRASAD','F82671','NHS HAVERING CCG',''),
('RAHMAN & TSOI','F82666','NHS HAVERING CCG',''),
('SPRING FARM SURGERY','F82607','NHS HAVERING CCG',''),
('THE GREEN WOOD PRACTICE','F82007','NHS HAVERING CCG',''),
('THE NEW MEDICAL CENTRE','F82021','NHS HAVERING CCG',''),
('THE ROBINS SURGERY, HAROLD HILL HEALTH C','Y00312','NHS HAVERING CCG',''),
('THE ROSEWOOD MEDICAL CENTRE','F82022','NHS HAVERING CCG',''),
('UPMINSTER BRIDGE SURGERY','F82624','NHS HAVERING CCG',''),
('UPMINSTER MEDICAL CENTRE','F82053','NHS HAVERING CCG',''),
('WESTERN ROAD MEDICAL CENTRE','F82013','NHS HAVERING CCG',''),
('WOOD LANE SURGERY','F82028','NHS HAVERING CCG',''),
('ALDERSBROOK MEDICAL CENTRE','F86731','NHS REDBRIDGE CCG',''),
('AT MEDICS - THE LOXFORD PRACTICE','Y02987','NHS REDBRIDGE CCG',''),
('BALFOUR ROAD SURGERY','F86042','NHS REDBRIDGE CCG',''),
('CASTLETON ROAD HEALTH CENTRE','F86642','NHS REDBRIDGE CCG',''),
('CHADWELL HEATH SURGERY','F86028','NHS REDBRIDGE CCG',''),
('CLAYHALL CLINIC','F86691','NHS REDBRIDGE CCG',''),
('CRANBROOK SURGERY','F86698','NHS REDBRIDGE CCG',''),
('FENCE PIECE ROAD MEDICAL CENTRE','F86707','NHS REDBRIDGE CCG',''),
('FULLWELL CROSS MED. CTR.','F86010','NHS REDBRIDGE CCG',''),
('GANTS HILL MEDICAL CENTRE','F86008','NHS REDBRIDGE CCG',''),
('GLEBELANDS PRACTICE','F86020','NHS REDBRIDGE CCG',''),
('GOODMAYES MEDICAL CENTRE','F86087','NHS REDBRIDGE CCG',''),
('GRANVILLE MEDICAL CENTRE','Y00918','NHS REDBRIDGE CCG',''),
('GREEN LANE, GOODMAYES MEDICAL PRACTICE','F86034','NHS REDBRIDGE CCG',''),
('GROVE SURGERY','Y00155','NHS REDBRIDGE CCG',''),
('HAINAULT SURGERY','F86085','NHS REDBRIDGE CCG',''),
('ILFORD LANE SURGERY','F86082','NHS REDBRIDGE CCG',''),
('ILFORD MEDICAL CENTRE','F86022','NHS REDBRIDGE CCG',''),
('KENWOOD MEDICAL','F86081','NHS REDBRIDGE CCG',''),
('MATHUKIA''S SURGERY','F86692','NHS REDBRIDGE CCG',''),
('NEWBURY GROUP PRACTICE','F86060','NHS REDBRIDGE CCG',''),
('OAK TREE MEDICAL CENTRE','F86025','NHS REDBRIDGE CCG',''),
('QUEEN MARY PRACTICE','F86658','NHS REDBRIDGE CCG',''),
('RYDAL','F86012','NHS REDBRIDGE CCG',''),
('SEVEN KINGS PRACTICE','F86637','NHS REDBRIDGE CCG',''),
('SOUTHDENE SURGERY','F86066','NHS REDBRIDGE CCG',''),
('ST CLEMENT''S SURGERY','F86702','NHS REDBRIDGE CCG',''),
('THE BROADWAY SURGERY','F86013','NHS REDBRIDGE CCG',''),
('THE DOCTORS HOUSE','Y00090','NHS REDBRIDGE CCG',''),
('THE DRIVE SURGERY','F86652','NHS REDBRIDGE CCG',''),
('THE EASTERN AVENUE MEDICAL CENTRE','F86083','NHS REDBRIDGE CCG',''),
('THE ELMHURST PRACTICE','F86064','NHS REDBRIDGE CCG',''),
('THE EVERGREEN SURGERY','F86023','NHS REDBRIDGE CCG',''),
('THE FOREST EDGE PRACTICE','F86007','NHS REDBRIDGE CCG',''),
('THE FULLWELL AVENUE SURGERY','F86612','NHS REDBRIDGE CCG',''),
('THE HEATHCOTE PRIMARY CARE CENTRE','F86624','NHS REDBRIDGE CCG',''),
('THE PALMS MEDICAL CENTRE','F86009','NHS REDBRIDGE CCG',''),
('THE REDBRIDGE SURGERY','F86703','NHS REDBRIDGE CCG',''),
('THE SHRUBBERIES MEDICAL CENTRE','F86641','NHS REDBRIDGE CCG',''),
('WANSTEAD PLACE SURGERY','F86032','NHS REDBRIDGE CCG',''),
('YORK ROAD SURGERY','F86657','NHS REDBRIDGE CCG','');


END//
DELIMITER ;