USE data_extracts;

-- ahui 17/3/2020

DROP PROCEDURE IF EXISTS populateHomeEncounters;

DELIMITER //

CREATE PROCEDURE populateHomeEncounters()
BEGIN

DROP TABLE IF EXISTS homeEncounters;

CREATE TABLE homeEncounters (
  id              INT,
  term            VARCHAR(200),
  PRIMARY KEY (id)
);

ALTER TABLE homeEncounters ADD INDEX home_idx (term);

INSERT INTO homeEncounters (id, term) 
VALUES 	
(1,'HOME VISIT NOTE'),
(2,'HOME VISIT'),
(3,'NURSING HOME VISIT NOTE'),
(4,'NIGHT VISIT'),
(5,'RESIDENTIAL HOME VISIT NOTE'),
(6,'DISTRICT NURSE VISIT'),
(7,'ACUTE VISIT'),
(8,'ON CALL VISIT'),
(9,'NURSING HOME'),
(10,'RESIDENTIAL HOME'),
(11,'CLINICAL, HOME VISITS'),
(12,'ADMINISTRATIVE, HOME VISITS'),
(13,'NURSING HOME ROUND'),
(14,'HOME VISIT-HARROW ROAD SURGERY'),
(15,'CHILDREN''S HOME VISIT NOTE'),
(16,'HARROW ROAD MEDICAL CENTRE-EXTENDED SU'),
(17,'DAYTIME VISITS PATIENTS HOME'),
(18,'DEPUTY VISITED'),
(19,'HOME OF PATIENT'),
(20,'NIGHT VISIT NOTE'),
(21,'NIGHT VISIT, DEPUTISING SERVICE'),
(22,'HOME VISIT - DAYTIME'),
(23,'FOLLOW-UP/ROUTINE VISIT'),
(24,'MANOR FARM NURSING HOME'),
(25,'EDWARD GIBBONS HOUSE'),
(26,'URGENT HOME VISIT'),
(27,'PATIENT''S HOME'),
(28,'HOME'),
(29,'ADMINISTRATIVE, HOME VISIT NOTE'),
(30,'NIGHT VISIT , PRACTICE'),
(31,'PATIENT HOME'),
(32,'SEEN IN OWN HOME'),
(33,'CEDAR LAWNS RESIDETIAL HOME'),
(34,'TWILIGHT VISIT NOTE'),
(35,'HOME VISIT EMERGENCY'),
(36,'FOLKESTONE NURSING HOME'),
(37,'HOME, HOME VISIT'),
(38,'CO-OP HOME VISIT'),
(39,'NIGHT VISIT (L.R.)'),
(40,'CLINICAL, HOME VISIT NOTE'),
(41,'RESIDENTIAL HOME VISIT'),
(42,'CHILDREN''S HOME VISIT'),
(43,'ST. PETERS HOME'),
(44,'NIGHT VISIT PATIENTS HOME'),
(45,'NIGHT VISIT, LOCAL ROTA'),
(46,'HEALTHCALL DAY VISIT'),
(47,'O O H HOME VISIT'),
(48,'CAMIDOC VISIT'),
(49,'CLINICAL, RESIDENTIAL HOME VISIT NOTE'),
(50,'TWILIGHT VISIT'),
(51,'LATE VISIT'),
(52,'DAY VISIT'),
(53,'NIGHT VISIT (H.R.)'),
(54,'NO ACCESS'),
(55,'THE DOC NIGHT VISIT'),
(56,'NURSING / RESIDENTIAL HOME'),
(57,'ETS VISIT'),
(58,'HOME VISIT NON PAYMENT'),
(59,'VISIT'),
(60,'DOMICILIARY CONSULTANT VISIT'),
(61,'HOME VISIT - IN SURGERY HOURS'),
(62,'NURSING HOME/CARE HOME (RESIDENTIAL HOME)'),
(63,'VISIT-HOME'),
(64,'HOME OF CLIENT'),
(65,'CLIENTS HOME'),
(66,'HOME, HOME'),
(67,'NIGHT VISIT - LOWER RATE'),
(68,'NIGHT VISIT LOCAL ROTA NOTE'),
(69,'NO ACCESS VISIT (HOME)'),
(70,'NURSING HOME VISIT'),
(71,'WEST ESSEX CHS STAFF, CLIENTS HOME'),
(72,'HOME VISIT (8AM-10PM)'),
(73,'HOME VISIT BY LIVER DOC'),
(74,'HOME VISIT REQUEST(TELEPHONIC MESSAGE)'),
(75,'G.P. HOME VISIT'),
(76,'HOME VISIT - IN HOURS'),
(77,'HOME VISIT - WORKING DAY'),
(78,'HOME VISIT REQUEST'),
(79,'NEW HOME VISIT'),
(80,'ACUTE HOME VISIT'),
(81,'CAMIDOC HOME VISIT'),
(82,'D N HOME VISIT'),
(83,'GP SURGERY, HOME VISIT'),
(84,'HOME VISIT (DAY)'),
(85,'HOME VISIT (PRACTICE)'),
(86,'HOME VISIT 6P.M. - 10P.M.'),
(87,'SELDOC - HOME VISIT HIGH RATE'),
(88,'COMMUNITY MATRON HOME VISIT'),
(89,'DEP.HOME VISIT DAYS.'),
(90,'FOLLOW-UP HOME VISIT'),
(91,'HOME VISIT (BARDOC)'),
(92,'HOME VISIT (NOT ON CALL)'),
(93,'HOME VISIT 10.30 - 6'),
(94,'HOME VISIT BY G.P.'),
(95,'HOME VISIT EARLY'),
(96,'HOME VISIT G.P.'),
(97,'HOME VISIT OUT OF SURGERY HOURS'),
(98,'HOME VISITS'),
(99,'HOME, HOME VISIT - HIGH FIELD SURGERY'),
(100,'LATE CALL HOME VISIT'),
(101,'LATE HOME VISIT'),
(102,'NORMED HOME VISIT'),
(103,'OOH HOME VISIT'),
(104,'OUTPATIENT MSK OT HOME VISIT NON CHARGE F/UP'),
(105,'OUTPATIENT MSK OT REHAB HOME VISIT NON CHARGE F/UP'),
(106,'OXCIDOCS HOME VISIT 8AM-10PM'),
(107,'REPEAT HOME VISIT'),
(108,'ROUTINE HOME VISIT'),
(109,'SELDOC - HOME VISIT'),
(110,'TUESDAY HOME VISIT');


ALTER TABLE homeEncounters ADD INDEX term_idx(term);

END //
DELIMITER ;
